spring:
  application:
    name: article-provider
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: xuehu-service-dev

dubbo:
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
#    serialization: kryo
#    optimizer: com.harusame.template.optimizer.SerializationOptimizerImpl

  cloud:
    # Dubbo 消费端订阅服务端的应用名，多个服务提供者用逗号分隔
    # 这里订阅"自己"，会被忽略掉，请根据实际情况添加
    subscribed-services: ${spring.application.name}
  scan:
    base-packages: com.harusame.template.service

mybatis-plus:
  type-aliases-package: com.harusame.template.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #standand 标准输出

server:
  port: 20870